config/routes.rb
Rails.application.routes.draw do
  resources :valve_positions
  resources :uplink_b_downlinks
  resources :time_uplinks
  resources :sensor1s
  resources :alarms
  resources :accumulators
  resources :uplinks
  resources :things
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/time_uplink.rb
class TimeUplink
  include Neo4j::ActiveNode
  property :value, type: String

    has_one :out, :uplink, type: :BELONGS_TO



end

app/controllers/time_uplinks_controller.rb
class TimeUplinksController < ApplicationController
  before_action :set_time_uplink, only: [:show, :edit, :update, :destroy]

  # GET /time_uplinks
  # GET /time_uplinks.json
  def index
    @time_uplinks = TimeUplink.all
  end

  # GET /time_uplinks/1
  # GET /time_uplinks/1.json
  def show
  end

  # GET /time_uplinks/new
  def new
    @time_uplink = TimeUplink.new
  end

  # GET /time_uplinks/1/edit
  def edit
  end

  # POST /time_uplinks
  # POST /time_uplinks.json
  def create
    @time_uplink = TimeUplink.new(time_uplink_params)

    respond_to do |format|
      if @time_uplink.save
        format.html { redirect_to @time_uplink, notice: 'Time uplink was successfully created.' }
        format.json { render :show, status: :created, location: @time_uplink }
      else
        format.html { render :new }
        format.json { render json: @time_uplink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_uplinks/1
  # PATCH/PUT /time_uplinks/1.json
  def update
    respond_to do |format|
      if @time_uplink.update(time_uplink_params)
        format.html { redirect_to @time_uplink, notice: 'Time uplink was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_uplink }
      else
        format.html { render :edit }
        format.json { render json: @time_uplink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_uplinks/1
  # DELETE /time_uplinks/1.json
  def destroy
    @time_uplink.destroy
    respond_to do |format|
      format.html { redirect_to time_uplinks_url, notice: 'Time uplink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_uplink
      @time_uplink = TimeUplink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_uplink_params
      params.require(:time_uplink).permit(:value, :uplink_id)
    end
end

app/helpers/time_uplinks_helper.rb
module TimeUplinksHelper
end

app/views/time_uplinks/_form.html.erb
<%= form_with(model: time_uplink, local: true) do |form| %>
  <% if time_uplink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_uplink.errors.count, "error") %> prohibited this time_uplink from being saved:</h2>

      <ul>
      <% time_uplink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :uplink_id %>
    <%= form.text_field :uplink_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/time_uplinks/edit.html.erb
<h1>Editing Time Uplink</h1>

<%= render 'form', time_uplink: @time_uplink %>

<%= link_to 'Show', @time_uplink %> |
<%= link_to 'Back', time_uplinks_path %>

app/views/time_uplinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Time Uplinks</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Uplink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @time_uplinks.each do |time_uplink| %>
      <tr>
        <td><%= time_uplink.value %></td>
        <td><%= time_uplink.uplink %></td>
        <td><%= link_to 'Show', time_uplink %></td>
        <td><%= link_to 'Edit', edit_time_uplink_path(time_uplink) %></td>
        <td><%= link_to 'Destroy', time_uplink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Time Uplink', new_time_uplink_path %>

app/views/time_uplinks/new.html.erb
<h1>New Time Uplink</h1>

<%= render 'form', time_uplink: @time_uplink %>

<%= link_to 'Back', time_uplinks_path %>

app/views/time_uplinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @time_uplink.value %>
</p>

<p>
  <strong>Uplink:</strong>
  <%= @time_uplink.uplink %>
</p>

<%= link_to 'Edit', edit_time_uplink_path(@time_uplink) %> |
<%= link_to 'Back', time_uplinks_path %>