config/routes.rb
Rails.application.routes.draw do
  resources :valve_positions
  resources :uplink_b_downlinks
  resources :time_uplinks
  resources :sensor1s
  resources :alarms
  resources :accumulators
  resources :uplinks
  resources :things
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/uplink.rb
class Uplink
  include Neo4j::ActiveNode
  property :data, type: String
  property :avgsnr, type: String
  property :rssi, type: String
  property :long, type: String
  property :lat, type: String
  property :snr, type: String

  has_one :in, :uplinks_created, type: :UPLINK_CREATED, model_class: :Thing

  has_one :in, :Alarm, type: :BELONGS_TO
  has_one :in, :Accumulator, type: :BELONGS_TO
  has_one :in, :Sensor1, type: :BELONGS_TO
  has_one :in, :TimeUplink, type: :BELONGS_TO
  has_one :in, :UplinkBDownlink, type: :BELONGS_TO
  has_one :in, :ValvePosition, type: :BELONGS_TO
end

app/controllers/uplinks_controller.rb
class UplinksController < ApplicationController
  before_action :set_uplink, only: [:show, :edit, :update, :destroy]

  # GET /uplinks
  # GET /uplinks.json
  def index
    @uplinks = Uplink.all
  end

  # GET /uplinks/1
  # GET /uplinks/1.json
  def show
  end

  # GET /uplinks/new
  def new
    @uplink = Uplink.new
  end

  # GET /uplinks/1/edit
  def edit
  end

  # POST /uplinks
  # POST /uplinks.json
  def create
    @uplink = Uplink.new(uplink_params)

    respond_to do |format|
      if @uplink.save
        format.html { redirect_to @uplink, notice: 'Uplink was successfully created.' }
        format.json { render :show, status: :created, location: @uplink }
      else
        format.html { render :new }
        format.json { render json: @uplink.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uplinks/1
  # PATCH/PUT /uplinks/1.json
  def update
    respond_to do |format|
      if @uplink.update(uplink_params)
        format.html { redirect_to @uplink, notice: 'Uplink was successfully updated.' }
        format.json { render :show, status: :ok, location: @uplink }
      else
        format.html { render :edit }
        format.json { render json: @uplink.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uplinks/1
  # DELETE /uplinks/1.json
  def destroy
    @uplink.destroy
    respond_to do |format|
      format.html { redirect_to uplinks_url, notice: 'Uplink was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uplink
      @uplink = Uplink.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uplink_params
      params.require(:uplink).permit(:data, :avgsnr, :rssi, :long, :lat, :snr, :thing_id)
    end
end

app/helpers/uplinks_helper.rb
module UplinksHelper
end

app/views/uplinks/_form.html.erb
<%= form_with(model: uplink, local: true) do |form| %>
  <% if uplink.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(uplink.errors.count, "error") %> prohibited this uplink from being saved:</h2>

      <ul>
      <% uplink.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="field">
    <%= form.label :avgsnr %>
    <%= form.text_field :avgsnr %>
  </div>

  <div class="field">
    <%= form.label :rssi %>
    <%= form.text_field :rssi %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :snr %>
    <%= form.text_field :snr %>
  </div>

  <div class="field">
    <%= form.label :thing_id %>
    <%= form.text_field :thing_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/uplinks/edit.html.erb
<h1>Editing Uplink</h1>

<%= render 'form', uplink: @uplink %>

<%= link_to 'Show', @uplink %> |
<%= link_to 'Back', uplinks_path %>

app/views/uplinks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Uplinks</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Avgsnr</th>
      <th>Rssi</th>
      <th>Long</th>
      <th>Lat</th>
      <th>Snr</th>
      <th>Thing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uplinks.each do |uplink| %>
      <tr>
        <td><%= uplink.data %></td>
        <td><%= uplink.avgsnr %></td>
        <td><%= uplink.rssi %></td>
        <td><%= uplink.long %></td>
        <td><%= uplink.lat %></td>
        <td><%= uplink.snr %></td>
        <td><%= uplink.thing %></td>
        <td><%= link_to 'Show', uplink %></td>
        <td><%= link_to 'Edit', edit_uplink_path(uplink) %></td>
        <td><%= link_to 'Destroy', uplink, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uplink', new_uplink_path %>

app/views/uplinks/new.html.erb
<h1>New Uplink</h1>

<%= render 'form', uplink: @uplink %>

<%= link_to 'Back', uplinks_path %>

app/views/uplinks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @uplink.data %>
</p>

<p>
  <strong>Avgsnr:</strong>
  <%= @uplink.avgsnr %>
</p>

<p>
  <strong>Rssi:</strong>
  <%= @uplink.rssi %>
</p>

<p>
  <strong>Long:</strong>
  <%= @uplink.long %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @uplink.lat %>
</p>

<p>
  <strong>Snr:</strong>
  <%= @uplink.snr %>
</p>

<p>
  <strong>Thing:</strong>
  <%= @uplink.thing %>
</p>

<%= link_to 'Edit', edit_uplink_path(@uplink) %> |
<%= link_to 'Back', uplinks_path %>