config/routes.rb
Rails.application.routes.draw do
  resources :valve_positions
  resources :uplink_b_downlinks
  resources :time_uplinks
  resources :sensor1s
  resources :alarms
  resources :accumulators
  resources :uplinks
  resources :things
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/valve_position.rb
class ValvePosition
  include Neo4j::ActiveNode
  property :value, type: String

  has_one :out, :uplink, type: :BELONGS_TO

end

app/controllers/valve_positions_controller.rb
class ValvePositionsController < ApplicationController
  before_action :set_valve_position, only: [:show, :edit, :update, :destroy]

  # GET /valve_positions
  # GET /valve_positions.json
  def index
    @valve_positions = ValvePosition.all
  end

  # GET /valve_positions/1
  # GET /valve_positions/1.json
  def show
  end

  # GET /valve_positions/new
  def new
    @valve_position = ValvePosition.new
  end

  # GET /valve_positions/1/edit
  def edit
  end

  # POST /valve_positions
  # POST /valve_positions.json
  def create
    @valve_position = ValvePosition.new(valve_position_params)

    respond_to do |format|
      if @valve_position.save
        format.html { redirect_to @valve_position, notice: 'Valve position was successfully created.' }
        format.json { render :show, status: :created, location: @valve_position }
      else
        format.html { render :new }
        format.json { render json: @valve_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /valve_positions/1
  # PATCH/PUT /valve_positions/1.json
  def update
    respond_to do |format|
      if @valve_position.update(valve_position_params)
        format.html { redirect_to @valve_position, notice: 'Valve position was successfully updated.' }
        format.json { render :show, status: :ok, location: @valve_position }
      else
        format.html { render :edit }
        format.json { render json: @valve_position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /valve_positions/1
  # DELETE /valve_positions/1.json
  def destroy
    @valve_position.destroy
    respond_to do |format|
      format.html { redirect_to valve_positions_url, notice: 'Valve position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_valve_position
      @valve_position = ValvePosition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def valve_position_params
      params.require(:valve_position).permit(:value, :uplink_id)
    end
end

app/helpers/valve_positions_helper.rb
module ValvePositionsHelper
end

app/views/valve_positions/_form.html.erb
<%= form_with(model: valve_position, local: true) do |form| %>
  <% if valve_position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(valve_position.errors.count, "error") %> prohibited this valve_position from being saved:</h2>

      <ul>
      <% valve_position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :uplink_id %>
    <%= form.text_field :uplink_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/valve_positions/edit.html.erb
<h1>Editing Valve Position</h1>

<%= render 'form', valve_position: @valve_position %>

<%= link_to 'Show', @valve_position %> |
<%= link_to 'Back', valve_positions_path %>

app/views/valve_positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Valve Positions</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Uplink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @valve_positions.each do |valve_position| %>
      <tr>
        <td><%= valve_position.value %></td>
        <td><%= valve_position.uplink %></td>
        <td><%= link_to 'Show', valve_position %></td>
        <td><%= link_to 'Edit', edit_valve_position_path(valve_position) %></td>
        <td><%= link_to 'Destroy', valve_position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Valve Position', new_valve_position_path %>

app/views/valve_positions/new.html.erb
<h1>New Valve Position</h1>

<%= render 'form', valve_position: @valve_position %>

<%= link_to 'Back', valve_positions_path %>

app/views/valve_positions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @valve_position.value %>
</p>

<p>
  <strong>Uplink:</strong>
  <%= @valve_position.uplink %>
</p>

<%= link_to 'Edit', edit_valve_position_path(@valve_position) %> |
<%= link_to 'Back', valve_positions_path %>